language: php

sudo: false

cache:
    directories:
        - $HOME/app/.composer/cache/files

php:
  - 7.4
  - nightly

env:
    global:
        - COMPOSER_MEMORY_LIMIT=-1
    matrix:
        - COMPOSER_PARAM="update --prefer-source --no-scripts --prefer-lowest --working-dir=app"
        - COMPOSER_PARAM="update --prefer-source --no-scripts --working-dir=app"

before_script:
    - cp app/config/parameters.yml.test var/config/parameters.yml
    - composer selfupdate
    - composer $COMPOSER_PARAM

script:
  - app/bin/phpunit --coverage-clover=coverage.clover --config=phpunit-no-database.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: nightly
