parameters:
    customization.app_title: Juvem
    customization.organization_website: null
    customization.organization_facebook: null
    customization.juvem_website: null
    customization.logo_website: null
    juvimg.url: null
    juvimg.password: null
    app.libreoffice_binary_path: null
    app.geo.openweathermap.api_key: null
    nextcloud.base_uri: null
    nextcloud.username: null
    nextcloud.password: null
    nextcloud.folder: 'Events'
    nextcloud.management: 'Management'
    nextcloud.team: 'Team'
    calendar.base_uri: null 
    calendar.public_uri: null
    calendar.username: null
    calendar.password: null
    backup_password: null
    app.gender.exclude: ''
    mailer_imap_host: null
    feature.registration: true
    required_participation_phone_number_count: 1
